class Solution:
    def convert(self, s: str, n: int) -> str:
        lst=[[] for _ in range(n)]
        


        i=0
        row=0
        
        while i != len(s):
            
            if  row<n:
                lst[row].append(s[i])

                i+=1
                row+=1
                

            else:
                zig=(n-2)

                
                row-=1
                
                for j in range(zig):

                    if i==len(s):
                        break
                    row-=1
                    
                    lst[row].append(s[i])
                    
                    
                    i+=1
                
                row-=1



        ans=""
        for i in lst:
            for j in i:
                ans+=j

        return ans

        







#convert("PAYPALISHIRING",5)

#convert("THEQUICKBROWNFOXJUMPSOVERTHELAZYDOGANDTHENRUNSTHROUGHTHEVALLEYOFMYSTERIESDISCOVERINGSECRETSBURIEDUNDERANCIENTRUINSWHERETHEWINDWHISPERSLEGENDSOFTHEPASTANDTHEMOONGLIMMERSOVERTHESILVERLAKEWHERETHETIMEFREEZESANDTHEDREAMERSAWAKETOCREATEWORLDSWITHWORDSSOGRANDTHEYECHOTHROUGHTHECOSMOSANDLIGHTUPTHESKYWITHIDEASUNBOUNDANDEVERLASTINGLIKEFLAMESOFDESIREBLAZINGINTHEHEARTOFINVENTIONNEVERSTOPPINGNEVERTIRINGONLYGROWINGSTRONGERWITHINTHEMINDSOFTHOSEWHODARETOIMAGINETHEIMPOSSIBLEANDTRANSFORMITINTOREALITYUNTILTHEFINALHOURWHENTHESTARSALIGNANDTHEVOICEOFCREATIONRISESTOHERALDAFUTURESOFARREACHINGITTOUCHESALLCORNERSTHATWEREDARKNESSANDFILLSITWITHTHELIGHTOFHUMANKINDTHEQUICKBROWNFOXJUMPSOVERTHELAZYDOGANDTHENRUNSTHROUGHTHEVALLEYOFMYSTERIESDISCOVERINGSECRETSBURIEDUNDERANCIENTRUINSWHERETHEWINDWHISPERSLEGENDSOFTHEPASTANDTHEMOONGLIMMERSOVERTHESILVERLAKEWHERETHETIMEFREEZESANDTHEDREAMERSAWAKETOCREATEWORLDSWITHWORDSSOGRANDTHEYECHOTHROUGHTHECOSMOSANDLIGHTUPTHESKYWITHIDEASUNBOUNDANDEVERLASTINGLIKEFLAMESOFDESIREBLAZINGINTHEHEARTOFINVENTIONNEVERSTOPPINGNEVERTIRINGONLYGROWINGSTRONGERWITHINTHEMINDSOFTHOSEWHODARETOIMAGINETHEIMPOSSIBLEANDTRANSFORMITINTOREALITYUNTILTHEFINALHOURWHENTHESTARSALIGNANDTHEVOICEOFCREATIONRISESTOHERALDAFUTURESOFARREACHINGITTOUCHESALLCORNERSTHATWEREDARKNESSANDFILLSITWITHTHELIGHTOFHUMANKIND", 1000)